inherit cmake pkgconfig

SUMMARY = "QTI open-source wrapper for Codec2"
SECTION = "multimedia"

LICENSE = "BSD-3-Clause-Clear"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta-qti-bsp/files/common-licenses/${LICENSE};md5=3771d4920bd6cdb8cbdf1e8344489ee0"

# Dependencies.
DEPENDS += "codec2"
DEPENDS:append:qrb5165 = " media-codec2"
DEPENDS:append:kalama = " media"
DEPENDS:append:kalama = " media-external"
DEPENDS:append:kalama = " audio-codec2"
DEPENDS:append:pineapple = " media"
DEPENDS:append:pineapple = " media-external"
DEPENDS:append:pineapple = " audio-codec2"
DEPENDS:append:kera = " media"
DEPENDS:append:kera = " media-external"
DEPENDS:append:kera = " audio-codec2"
DEPENDS:append:alor = " media"
DEPENDS:append:alor = " media-external"
DEPENDS:append:alor = " audio-codec2"
DEPENDS:append:pebble = " media"
DEPENDS:append:pebble = " media-external"
DEPENDS:append:pebble = " audio-codec2"
DEPENDS:append:bengal = " media"
DEPENDS:append:bengal = " media-external"
DEPENDS:append:bengal = " mm-audio-headers"
DEPENDS:append:bengal = " audio-codec2"
DEPENDS:append:sun = " media"
DEPENDS:append:sun = " media-external"
DEPENDS:append:sun = " mm-audio-headers"
DEPENDS:append:sun = " audio-codec2"
DEPENDS:append:vienna = " media"
DEPENDS:append:vienna = " media-external"

FILESPATH =+ "${WORKSPACE}/vendor/qcom/opensource/iot-core-oss/:"

SRC_URI = "file://c2-module/"
S = "${WORKDIR}/c2-module"

# Install directries.
INSTALL_BINDIR := "${bindir}"
INSTALL_LIBDIR := "${libdir}"
INSTALL_INCDIR := "${includedir}"

CODEC2_CONFIG_VERSION_MAJOR := "1"
CODEC2_CONFIG_VERSION_MAJOR:kalama := "2"
CODEC2_CONFIG_VERSION_MAJOR:pineapple := "2"
CODEC2_CONFIG_VERSION_MAJOR:kera := "2"
CODEC2_CONFIG_VERSION_MAJOR:alor := "2"
CODEC2_CONFIG_VERSION_MAJOR:bengal := "2"
CODEC2_CONFIG_VERSION_MAJOR:sun := "2"
CODEC2_CONFIG_VERSION_MAJOR:vienna := "2"
CODEC2_CONFIG_VERSION_MAJOR:pebble := "2"

CODEC2_CONFIG_VERSION_MINOR := "0"
CODEC2_CONFIG_VERSION_MINOR:kalama := "1"
CODEC2_CONFIG_VERSION_MINOR:pineapple := "1"
CODEC2_CONFIG_VERSION_MINOR:kera := "1"
CODEC2_CONFIG_VERSION_MINOR:alor := "1"
CODEC2_CONFIG_VERSION_MINOR:sun := "1"
CODEC2_CONFIG_VERSION_MINOR:pebble := "1"

ENABLE_AUDIO_PLUGINS:kalama := "TRUE"
ENABLE_AUDIO_PLUGINS:pineapple := "TRUE"
ENABLE_AUDIO_PLUGINS:kera := "TRUE"
ENABLE_AUDIO_PLUGINS:alor := "TRUE"
ENABLE_AUDIO_PLUGINS:bengal := "TRUE"
ENABLE_AUDIO_PLUGINS:sun := "TRUE"
ENABLE_AUDIO_PLUGINS:vienna := "TRUE"
ENABLE_AUDIO_PLUGINS:pebble := "TRUE"

EXTRA_OECMAKE += "-DSYSROOT_INCDIR=${STAGING_INCDIR}"
EXTRA_OECMAKE += "-DSYSROOT_LIBDIR=${STAGING_LIBDIR}"
EXTRA_OECMAKE += "-DKERNEL_BUILDDIR=${STAGING_INCDIR}/linux-msm"
EXTRA_OECMAKE += "-DIOT_CORE_OSS_INSTALL_INCDIR=${INSTALL_INCDIR}"
EXTRA_OECMAKE += "-DIOT_CORE_OSS_INSTALL_BINDIR=${INSTALL_BINDIR}"
EXTRA_OECMAKE += "-DIOT_CORE_OSS_INSTALL_LIBDIR=${INSTALL_LIBDIR}"
EXTRA_OECMAKE += "-DGST_ENABLE_AUDIO_PLUGINS=${ENABLE_AUDIO_PLUGINS}"

EXTRA_OECMAKE += "-DGST_CODEC2_CONFIG_VERSION_MAJOR=${CODEC2_CONFIG_VERSION_MAJOR}"
EXTRA_OECMAKE += "-DGST_CODEC2_CONFIG_VERSION_MINOR=${CODEC2_CONFIG_VERSION_MINOR}"

FILES:${PN} += "${INSTALL_BINDIR}"
FILES:${PN} += "${INSTALL_LIBDIR}"

SOLIBS = ".so*"
FILES_SOLIBSDEV = ""
TOOLCHAIN = "sdllvm"
TOOLCHAIN:pebble = "aospllvm"
DEBUG_PREFIX_MAP:remove = "-fcanon-prefix-map"
