BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-qmmf"
BBFILE_PRIORITY_qti-qmmf = "12"
BBFILE_PATTERN_qti-qmmf := "^${LAYERDIR}/"
