# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*/*.bb"

BBFILE_COLLECTIONS += "qti-qmmf"
BBFILE_PATTERN_qti-qmmf = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-qmmf = "10"

LAYERSERIES_COMPAT_qti-qmmf = "dunfell scarthgap"

LAYERVERSION_qti-qmmf = "1"
